<?php

namespace Database\Seeders;

use App\Models\EdukasiGratis;
use Illuminate\Database\Seeder;

class EdukasiGratisSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'judul' => 'GitHub Student Developer Pack',
                'deskripsi' => 'Akses 100+ tools developer premium gratis termasuk GitHub Pro, domain gratis, cloud credits, dan banyak lagi. Cocok untuk mahasiswa aktif.',
                'langkah' => '<ol><li>Kunjungi <a href="https://education.github.com/pack" target="_blank">education.github.com/pack</a></li><li>Klik "Get your pack" dan login dengan akun GitHub</li><li>Pilih "Student" dan verifikasi status pendidikan kamu</li><li>Upload foto KTM atau bukti mahasiswa aktif</li><li>Tunggu verifikasi 1-7 hari kerja</li><li>Setelah disetujui, akses semua tools gratis di dashboard</li></ol>',
                'kategori' => 'tools',
                'platform' => 'GitHub',
                'url_resmi' => 'https://education.github.com/pack',
                'ikon' => 'fab fa-github',
                'warna' => 'kvt',
                'unggulan' => true,
                'urutan' => 1,
            ],
            [
                'judul' => 'Figma Education Plan (Gratis)',
                'deskripsi' => 'Dapatkan Figma Professional gratis untuk mahasiswa dan pengajar. Termasuk unlimited projects, team libraries, dan fitur premium lainnya.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.figma.com/education/" target="_blank">figma.com/education</a></li><li>Klik "Get Verified" dan buat akun Figma</li><li>Gunakan email kampus (.ac.id / .edu)</li><li>Isi formulir verifikasi dengan data kampus</li><li>Upload bukti status mahasiswa/pengajar</li><li>Verifikasi biasanya selesai dalam 24-48 jam</li></ol>',
                'kategori' => 'design',
                'platform' => 'Figma',
                'url_resmi' => 'https://www.figma.com/education/',
                'ikon' => 'fab fa-figma',
                'warna' => 'purple',
                'unggulan' => true,
                'urutan' => 2,
            ],
            [
                'judul' => 'JetBrains Student License (All IDEs)',
                'deskripsi' => 'Akses gratis ke semua IDE JetBrains — IntelliJ IDEA, PyCharm, WebStorm, PhpStorm, dll. Berlaku selama masih berstatus mahasiswa.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.jetbrains.com/community/education/" target="_blank">jetbrains.com/community/education</a></li><li>Klik "Apply Now"</li><li>Gunakan email kampus (.ac.id / .edu)</li><li>Atau upload bukti KTM / surat keterangan mahasiswa aktif</li><li>Verifikasi otomatis jika domain email dikenali</li><li>Download IDE yang diinginkan dan aktifkan dengan akun JetBrains</li></ol>',
                'kategori' => 'tools',
                'platform' => 'JetBrains',
                'url_resmi' => 'https://www.jetbrains.com/community/education/',
                'ikon' => 'fas fa-laptop-code',
                'warna' => 'orange',
                'unggulan' => true,
                'urutan' => 3,
            ],
            [
                'judul' => 'Microsoft Azure for Students ($100 Credit)',
                'deskripsi' => 'Dapatkan $100 kredit Azure gratis tanpa kartu kredit, plus akses ke 25+ layanan cloud Azure secara gratis selama 12 bulan.',
                'langkah' => '<ol><li>Kunjungi <a href="https://azure.microsoft.com/en-us/free/students/" target="_blank">azure.microsoft.com/free/students</a></li><li>Klik "Start Free" dan login dengan akun Microsoft</li><li>Verifikasi menggunakan email kampus (.ac.id / .edu)</li><li>Tidak perlu kartu kredit — cukup email kampus</li><li>Kredit $100 otomatis ditambahkan ke akun</li><li>Akses VM, database, AI services, dan lainnya</li></ol>',
                'kategori' => 'cloud',
                'platform' => 'Microsoft',
                'url_resmi' => 'https://azure.microsoft.com/en-us/free/students/',
                'ikon' => 'fab fa-microsoft',
                'warna' => 'kvt',
                'unggulan' => true,
                'urutan' => 4,
            ],
            [
                'judul' => 'Google Cloud for Education ($300 Credit)',
                'deskripsi' => 'Google Cloud Platform memberikan $300 kredit gratis selama 90 hari untuk semua pengguna baru. Akses 20+ produk cloud gratis.',
                'langkah' => '<ol><li>Kunjungi <a href="https://cloud.google.com/free" target="_blank">cloud.google.com/free</a></li><li>Klik "Get started for free" dan login ke akun Google</li><li>Masukkan informasi pembayaran (tidak akan dicharge)</li><li>Kredit $300 otomatis tersedia selama 90 hari</li><li>Gunakan untuk Compute Engine, BigQuery, Cloud Storage, dll</li><li>Setelah trial berakhir, tetap gratis untuk tier-free products</li></ol>',
                'kategori' => 'cloud',
                'platform' => 'Google',
                'url_resmi' => 'https://cloud.google.com/free',
                'ikon' => 'fab fa-google',
                'warna' => 'green',
                'unggulan' => true,
                'urutan' => 5,
            ],
            [
                'judul' => 'AWS Educate (Cloud Computing Gratis)',
                'deskripsi' => 'Program gratis dari Amazon Web Services untuk belajar cloud computing. Termasuk lab hands-on, kredit AWS, dan sertifikat badges.',
                'langkah' => '<ol><li>Kunjungi <a href="https://aws.amazon.com/education/awseducate/" target="_blank">aws.amazon.com/education/awseducate</a></li><li>Klik "Join AWS Educate"</li><li>Pilih peran: Student, Educator, atau Institution</li><li>Isi formulir dan verifikasi email kampus</li><li>Akses cloud labs, career pathways, dan job board</li><li>Dapatkan badges setelah menyelesaikan modul</li></ol>',
                'kategori' => 'cloud',
                'platform' => 'Amazon',
                'url_resmi' => 'https://aws.amazon.com/education/awseducate/',
                'ikon' => 'fab fa-aws',
                'warna' => 'amber',
                'unggulan' => true,
                'urutan' => 6,
            ],
            [
                'judul' => 'Canva for Education (Pro Gratis)',
                'deskripsi' => 'Canva Pro gratis selamanya untuk pelajar dan pengajar. Akses 100+ juta foto, video, template premium, dan fitur AI.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.canva.com/education/" target="_blank">canva.com/education</a></li><li>Klik "Get verified" sebagai student atau teacher</li><li>Buat akun menggunakan email kampus</li><li>Verifikasi identitas sebagai pelajar/pengajar</li><li>Setelah disetujui, akun otomatis upgrade ke Canva Pro</li><li>Akses semua fitur premium termasuk Brand Kit, Magic Resize, dll</li></ol>',
                'kategori' => 'design',
                'platform' => 'Canva',
                'url_resmi' => 'https://www.canva.com/education/',
                'ikon' => 'fas fa-palette',
                'warna' => 'cyan',
                'unggulan' => false,
                'urutan' => 7,
            ],
            [
                'judul' => 'Notion for Education (Plus Plan Gratis)',
                'deskripsi' => 'Notion Plus Plan gratis untuk mahasiswa dan pengajar. Unlimited blocks, file uploads, dan guest collaborators.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.notion.so/product/notion-for-education" target="_blank">notion.so/product/notion-for-education</a></li><li>Daftar dengan email kampus (.ac.id / .edu)</li><li>Buka Settings & Members > Upgrade</li><li>Pilih "Education Plan" — akan otomatis gratis</li><li>Akses unlimited blocks, file uploads 5GB, dan fitur Plus lainnya</li></ol>',
                'kategori' => 'produktivitas',
                'platform' => 'Notion',
                'url_resmi' => 'https://www.notion.so/product/notion-for-education',
                'ikon' => 'fas fa-sticky-note',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 8,
            ],
            [
                'judul' => 'Microsoft 365 Education (Gratis)',
                'deskripsi' => 'Akses lengkap Word, Excel, PowerPoint, Teams, OneDrive 1TB, dan semua apps Microsoft 365 gratis untuk pelajar dan pengajar.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.microsoft.com/en-us/education/products/office" target="_blank">microsoft.com/education/products/office</a></li><li>Masukkan email kampus di kolom verifikasi</li><li>Jika domain kampus sudah terdaftar, akses langsung diberikan</li><li>Jika belum, hubungi IT kampus untuk mendaftarkan domain</li><li>Login ke office.com dengan akun kampus</li><li>Download apps desktop atau gunakan versi web gratis</li></ol>',
                'kategori' => 'produktivitas',
                'platform' => 'Microsoft',
                'url_resmi' => 'https://www.microsoft.com/en-us/education/products/office',
                'ikon' => 'fab fa-microsoft',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 9,
            ],
            [
                'judul' => 'Google Workspace for Education',
                'deskripsi' => 'Suite lengkap Google — Gmail, Drive unlimited, Docs, Sheets, Slides, Meet, Classroom, dan lainnya. Gratis untuk institusi pendidikan.',
                'langkah' => '<ol><li>Kunjungi <a href="https://edu.google.com/workspace-for-education/" target="_blank">edu.google.com/workspace-for-education</a></li><li>Kampus/sekolah harus mendaftar terlebih dahulu</li><li>Hubungi IT kampus untuk mendapatkan akun Google Workspace</li><li>Login dengan akun kampus (email @kampus.ac.id)</li><li>Akses Drive unlimited, Meet premium, Classroom, dan semua apps</li></ol>',
                'kategori' => 'produktivitas',
                'platform' => 'Google',
                'url_resmi' => 'https://edu.google.com/workspace-for-education/',
                'ikon' => 'fab fa-google',
                'warna' => 'green',
                'unggulan' => false,
                'urutan' => 10,
            ],
            [
                'judul' => 'Coursera for Campus (Courses Gratis)',
                'deskripsi' => 'Akses ribuan kursus dari universitas top dunia (Stanford, Yale, Google) secara gratis melalui program Coursera for Campus.',
                'langkah' => '<ol><li>Cek apakah kampusmu terdaftar di <a href="https://www.coursera.org/campus" target="_blank">coursera.org/campus</a></li><li>Jika ya, daftar menggunakan email kampus</li><li>Akses kursus yang ditentukan kampus secara gratis</li><li>Untuk individu: Apply "Financial Aid" per kursus (100% gratis)</li><li>Isi form alasan membutuhkan bantuan finansial</li><li>Persetujuan biasanya dalam 15 hari — akses penuh + sertifikat</li></ol>',
                'kategori' => 'pendidikan',
                'platform' => 'Coursera',
                'url_resmi' => 'https://www.coursera.org/campus',
                'ikon' => 'fas fa-graduation-cap',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 11,
            ],
            [
                'judul' => 'edX Free Courses & Audit Track',
                'deskripsi' => 'Platform edX menawarkan ribuan kursus gratis dari Harvard, MIT, Berkeley. Audit track memungkinkan akses materi tanpa biaya.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.edx.org/" target="_blank">edx.org</a></li><li>Buat akun gratis dan cari kursus yang diinginkan</li><li>Pilih opsi "Audit This Course" (gratis)</li><li>Akses semua materi video, reading, dan quiz</li><li>Untuk sertifikat, bisa apply financial assistance (gratis juga)</li><li>Program MicroMasters juga tersedia untuk audit gratis</li></ol>',
                'kategori' => 'pendidikan',
                'platform' => 'edX',
                'url_resmi' => 'https://www.edx.org/',
                'ikon' => 'fas fa-book-open',
                'warna' => 'red',
                'unggulan' => false,
                'urutan' => 12,
            ],
            [
                'judul' => 'freeCodeCamp (Full Stack Gratis)',
                'deskripsi' => 'Platform coding gratis dan open-source. Belajar Web Development, Data Science, Machine Learning, dan dapatkan sertifikasi gratis.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.freecodecamp.org/" target="_blank">freecodecamp.org</a></li><li>Buat akun gratis (cukup email)</li><li>Pilih curriculum: Responsive Design, JavaScript, Python, dll</li><li>Selesaikan projects untuk mendapatkan sertifikat</li><li>Semua materi 100% gratis, tidak ada paywall</li><li>6 sertifikasi tersedia, masing-masing ~300 jam belajar</li></ol>',
                'kategori' => 'pendidikan',
                'platform' => 'freeCodeCamp',
                'url_resmi' => 'https://www.freecodecamp.org/',
                'ikon' => 'fab fa-free-code-camp',
                'warna' => 'green',
                'unggulan' => false,
                'urutan' => 13,
            ],
            [
                'judul' => 'Udemy Free Courses (Kursus Gratis)',
                'deskripsi' => 'Udemy menyediakan ribuan kursus gratis di berbagai bidang: programming, design, marketing, business, dan personal development.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.udemy.com/courses/free/" target="_blank">udemy.com/courses/free</a></li><li>Filter berdasarkan topik yang diminati</li><li>Buat akun Udemy gratis</li><li>Enroll kursus gratis — langsung akses</li><li>Banyak juga kupon gratis dari instruktur (cari di Google/Reddit)</li><li>Kursus gratis tetap bisa diakses selamanya setelah enroll</li></ol>',
                'kategori' => 'pendidikan',
                'platform' => 'Udemy',
                'url_resmi' => 'https://www.udemy.com/courses/free/',
                'ikon' => 'fas fa-play-circle',
                'warna' => 'purple',
                'unggulan' => false,
                'urutan' => 14,
            ],
            [
                'judul' => 'Khan Academy (Semua Gratis)',
                'deskripsi' => 'Platform pembelajaran gratis dari SD hingga kuliah. Matematika, Sains, Ekonomi, Komputer, SAT Prep — semuanya 100% gratis.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.khanacademy.org/" target="_blank">khanacademy.org</a></li><li>Buat akun gratis atau login dengan Google</li><li>Pilih subjek yang ingin dipelajari</li><li>Tonton video, kerjakan latihan interaktif</li><li>Track progress dan dapatkan badges</li><li>Nonprofit — semuanya gratis, tidak ada subscription/paywall</li></ol>',
                'kategori' => 'pendidikan',
                'platform' => 'Khan Academy',
                'url_resmi' => 'https://www.khanacademy.org/',
                'ikon' => 'fas fa-chalkboard-teacher',
                'warna' => 'green',
                'unggulan' => false,
                'urutan' => 15,
            ],
            [
                'judul' => 'Autodesk Education (Maya, 3ds Max, AutoCAD Gratis)',
                'deskripsi' => 'Semua software Autodesk gratis untuk mahasiswa dan pengajar — AutoCAD, Maya, 3ds Max, Fusion 360, Revit, dan lainnya.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.autodesk.com/education/edu-software/" target="_blank">autodesk.com/education/edu-software</a></li><li>Buat akun Autodesk Education</li><li>Verifikasi status mahasiswa/pengajar</li><li>Upload bukti pendidikan (KTM/surat keterangan)</li><li>Setelah diverifikasi, download semua software gratis</li><li>Lisensi berlaku 1 tahun dan bisa diperpanjang selama masih kuliah</li></ol>',
                'kategori' => 'design',
                'platform' => 'Autodesk',
                'url_resmi' => 'https://www.autodesk.com/education/edu-software/',
                'ikon' => 'fas fa-cube',
                'warna' => 'cyan',
                'unggulan' => false,
                'urutan' => 16,
            ],
            [
                'judul' => 'Unity Student Plan (Game Dev Gratis)',
                'deskripsi' => 'Unity Student Plan gratis untuk mahasiswa. Termasuk Unity Pro, cloud build, premium learning resources, dan asset packs.',
                'langkah' => '<ol><li>Kunjungi <a href="https://unity.com/products/unity-student" target="_blank">unity.com/products/unity-student</a></li><li>Verifikasi status mahasiswa melalui SheerID</li><li>Buat akun Unity ID dan link ke student plan</li><li>Download Unity Hub dan install editor</li><li>Akses Unity Learn premium content gratis</li><li>Termasuk Plastic SCM, Cloud Build, dan Collaborate</li></ol>',
                'kategori' => 'dev',
                'platform' => 'Unity',
                'url_resmi' => 'https://unity.com/products/unity-student',
                'ikon' => 'fab fa-unity',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 17,
            ],
            [
                'judul' => 'Tableau for Students (Data Viz Gratis)',
                'deskripsi' => 'Tableau Desktop dan Tableau Prep gratis 1 tahun untuk mahasiswa. Tools visualisasi data profesional yang digunakan di industri.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.tableau.com/academic/students" target="_blank">tableau.com/academic/students</a></li><li>Klik "Get Tableau for Free"</li><li>Isi formulir dengan email kampus</li><li>Verifikasi otomatis melalui email .edu/.ac.id</li><li>Download Tableau Desktop dan Tableau Prep</li><li>Lisensi 1 tahun, bisa diperpanjang selama masih kuliah</li></ol>',
                'kategori' => 'tools',
                'platform' => 'Tableau',
                'url_resmi' => 'https://www.tableau.com/academic/students',
                'ikon' => 'fas fa-chart-bar',
                'warna' => 'amber',
                'unggulan' => false,
                'urutan' => 18,
            ],
            [
                'judul' => 'Notion AI (Free for Students)',
                'deskripsi' => 'Notion AI gratis untuk pengguna Education Plan. Gunakan AI untuk menulis, brainstorm, summarize, dan translate langsung di workspace.',
                'langkah' => '<ol><li>Pastikan sudah memiliki Notion Education Plan</li><li>Buka Settings > Upgrade > Notion AI</li><li>Jika sudah di Education Plan, AI fitur gratis atau discounted</li><li>Gunakan AI untuk auto-complete, summarize notes, brainstorm</li><li>Terintegrasi langsung di semua halaman Notion</li></ol>',
                'kategori' => 'ai',
                'platform' => 'Notion',
                'url_resmi' => 'https://www.notion.so/product/ai',
                'ikon' => 'fas fa-robot',
                'warna' => 'purple',
                'unggulan' => false,
                'urutan' => 19,
            ],
            [
                'judul' => 'MongoDB Atlas Student Pack',
                'deskripsi' => 'MongoDB Atlas free tier + $200 credit untuk mahasiswa melalui GitHub Student Pack. Database NoSQL cloud gratis.',
                'langkah' => '<ol><li>Aktifkan GitHub Student Developer Pack terlebih dahulu</li><li>Kunjungi <a href="https://www.mongodb.com/students" target="_blank">mongodb.com/students</a></li><li>Claim benefit MongoDB melalui GitHub Education</li><li>Buat cluster free tier (512MB) — gratis selamanya</li><li>Gunakan credit $200 untuk dedicated clusters</li><li>Termasuk MongoDB University courses gratis</li></ol>',
                'kategori' => 'database',
                'platform' => 'MongoDB',
                'url_resmi' => 'https://www.mongodb.com/students',
                'ikon' => 'fas fa-database',
                'warna' => 'green',
                'unggulan' => false,
                'urutan' => 20,
            ],
            [
                'judul' => 'Vercel Pro (Free for Students)',
                'deskripsi' => 'Vercel Pro gratis untuk mahasiswa melalui GitHub Student Pack. Deploy website Next.js, React, Vue dengan performa tinggi.',
                'langkah' => '<ol><li>Aktifkan GitHub Student Developer Pack</li><li>Kunjungi <a href="https://vercel.com/docs/accounts/education" target="_blank">Vercel Education</a></li><li>Connect akun GitHub yang sudah terverifikasi student</li><li>Vercel Pro otomatis aktif — gratis selama berstatus mahasiswa</li><li>Akses analytics, preview deployments, dan serverless functions lebih banyak</li></ol>',
                'kategori' => 'cloud',
                'platform' => 'Vercel',
                'url_resmi' => 'https://vercel.com/docs/accounts/education',
                'ikon' => 'fas fa-rocket',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 21,
            ],
            [
                'judul' => 'DigitalOcean Student Credit ($200)',
                'deskripsi' => 'Kredit $200 DigitalOcean gratis untuk mahasiswa melalui GitHub Student Pack. Buat droplets, deploy apps, dan belajar cloud.',
                'langkah' => '<ol><li>Aktifkan GitHub Student Developer Pack</li><li>Kunjungi <a href="https://www.digitalocean.com/github-students" target="_blank">digitalocean.com/github-students</a></li><li>Login dengan akun GitHub yang terverifikasi student</li><li>Claim kredit $200 — berlaku 1 tahun</li><li>Buat Droplets, Kubernetes, databases, dan lainnya</li><li>Cocok untuk belajar DevOps dan cloud computing</li></ol>',
                'kategori' => 'cloud',
                'platform' => 'DigitalOcean',
                'url_resmi' => 'https://www.digitalocean.com/github-students',
                'ikon' => 'fab fa-digital-ocean',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 22,
            ],
            [
                'judul' => 'Namecheap Free Domain (.me)',
                'deskripsi' => 'Domain .me gratis 1 tahun + SSL certificate gratis untuk mahasiswa melalui GitHub Student Developer Pack.',
                'langkah' => '<ol><li>Aktifkan GitHub Student Developer Pack</li><li>Kunjungi benefit Namecheap di GitHub Education</li><li>Klik "Get your free .me domain"</li><li>Pilih nama domain .me yang diinginkan</li><li>Checkout — harga $0 untuk tahun pertama</li><li>Termasuk SSL certificate gratis dan WhoisGuard</li></ol>',
                'kategori' => 'tools',
                'platform' => 'Namecheap',
                'url_resmi' => 'https://www.namecheap.com/education-program/',
                'ikon' => 'fas fa-globe',
                'warna' => 'orange',
                'unggulan' => false,
                'urutan' => 23,
            ],
            [
                'judul' => 'Replit Core (Free for Students)',
                'deskripsi' => 'IDE online gratis dengan AI coding assistant. Tulis, jalankan, dan deploy code langsung dari browser tanpa setup.',
                'langkah' => '<ol><li>Kunjungi <a href="https://replit.com/site/github-students" target="_blank">replit.com/site/github-students</a></li><li>Connect akun GitHub Student</li><li>Claim Replit Core plan gratis</li><li>Akses Ghostwriter AI, lebih banyak compute, dan private Repls</li><li>Support 50+ bahasa pemrograman</li><li>Deploy langsung ke custom domain</li></ol>',
                'kategori' => 'dev',
                'platform' => 'Replit',
                'url_resmi' => 'https://replit.com/site/github-students',
                'ikon' => 'fas fa-code',
                'warna' => 'amber',
                'unggulan' => false,
                'urutan' => 24,
            ],
            [
                'judul' => 'Google Colab (ML/AI Gratis)',
                'deskripsi' => 'Jupyter Notebook gratis di cloud dari Google. Termasuk akses GPU/TPU gratis untuk machine learning dan data science.',
                'langkah' => '<ol><li>Kunjungi <a href="https://colab.research.google.com/" target="_blank">colab.research.google.com</a></li><li>Login dengan akun Google (apapun — gratis)</li><li>Buat notebook baru atau upload .ipynb</li><li>Pilih Runtime > Change runtime type > GPU (gratis)</li><li>Jalankan kode Python dengan library ML pre-installed</li><li>Save otomatis ke Google Drive</li></ol>',
                'kategori' => 'ai',
                'platform' => 'Google',
                'url_resmi' => 'https://colab.research.google.com/',
                'ikon' => 'fas fa-brain',
                'warna' => 'amber',
                'unggulan' => false,
                'urutan' => 25,
            ],
            [
                'judul' => 'Kaggle Learn (Data Science Gratis)',
                'deskripsi' => 'Platform belajar Data Science, ML, dan AI dari Google. Kursus gratis, dataset publik, kompetisi, dan GPU gratis untuk notebook.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.kaggle.com/learn" target="_blank">kaggle.com/learn</a></li><li>Buat akun Kaggle gratis (atau login dengan Google)</li><li>Pilih kursus: Python, Pandas, ML, Deep Learning, SQL, dll</li><li>Selesaikan exercises di setiap lesson</li><li>Dapatkan sertifikat setelah menyelesaikan kursus</li><li>Akses free GPU (30 jam/minggu) di Kaggle Notebooks</li></ol>',
                'kategori' => 'ai',
                'platform' => 'Kaggle (Google)',
                'url_resmi' => 'https://www.kaggle.com/learn',
                'ikon' => 'fas fa-chart-line',
                'warna' => 'cyan',
                'unggulan' => false,
                'urutan' => 26,
            ],
            [
                'judul' => 'Cloudflare for Education',
                'deskripsi' => 'Cloudflare Pages, Workers, R2 Storage gratis untuk project pendidikan. CDN global, DDoS protection, dan SSL gratis.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.cloudflare.com/plans/free/" target="_blank">cloudflare.com/plans/free</a></li><li>Buat akun Cloudflare (gratis untuk siapa saja)</li><li>Free plan sudah termasuk CDN, SSL, DDoS protection</li><li>Cloudflare Pages: deploy unlimited static sites gratis</li><li>Workers: 100K request/hari gratis</li><li>R2 Storage: 10GB gratis — cocok untuk project mahasiswa</li></ol>',
                'kategori' => 'cloud',
                'platform' => 'Cloudflare',
                'url_resmi' => 'https://www.cloudflare.com/plans/free/',
                'ikon' => 'fas fa-cloud',
                'warna' => 'orange',
                'unggulan' => false,
                'urutan' => 27,
            ],
            [
                'judul' => 'LinkedIn Learning (via Library Card)',
                'deskripsi' => 'Akses ribuan kursus LinkedIn Learning gratis melalui kartu perpustakaan daerah. Business, tech, creative — semua ada.',
                'langkah' => '<ol><li>Daftar kartu perpustakaan di perpustakaan daerah/kota terdekat (gratis)</li><li>Kunjungi <a href="https://www.linkedin.com/learning/" target="_blank">linkedin.com/learning</a></li><li>Pilih opsi "Sign in with your library card"</li><li>Masukkan nomor kartu perpustakaan</li><li>Akses 16,000+ kursus gratis tanpa batas</li><li>Beberapa kampus juga menyediakan akses langsung</li></ol>',
                'kategori' => 'pendidikan',
                'platform' => 'LinkedIn',
                'url_resmi' => 'https://www.linkedin.com/learning/',
                'ikon' => 'fab fa-linkedin',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 28,
            ],
            [
                'judul' => 'HackerRank (Practice & Certify Free)',
                'deskripsi' => 'Platform latihan coding gratis. Practice challenges di berbagai bahasa dan dapatkan sertifikasi skills yang diakui recruiter.',
                'langkah' => '<ol><li>Kunjungi <a href="https://www.hackerrank.com/" target="_blank">hackerrank.com</a></li><li>Buat akun gratis</li><li>Pilih domain: Algorithms, Data Structures, Python, SQL, dll</li><li>Selesaikan challenges dan naik level</li><li>Ambil Skills Certification test (gratis)</li><li>Sertifikat bisa ditampilkan di LinkedIn dan resume</li></ol>',
                'kategori' => 'sertifikasi',
                'platform' => 'HackerRank',
                'url_resmi' => 'https://www.hackerrank.com/',
                'ikon' => 'fas fa-code',
                'warna' => 'green',
                'unggulan' => false,
                'urutan' => 29,
            ],
            [
                'judul' => '1Password Student (Free via GitHub)',
                'deskripsi' => 'Password manager 1Password gratis 1 tahun untuk mahasiswa melalui GitHub Student Developer Pack. Simpan password dengan aman.',
                'langkah' => '<ol><li>Aktifkan GitHub Student Developer Pack</li><li>Cari benefit 1Password di halaman GitHub Education</li><li>Klik link claim dan buat akun 1Password</li><li>Masukkan kode promo dari GitHub</li><li>Akses 1Password selama 1 tahun secara gratis</li><li>Simpan unlimited passwords, documents, dan secure notes</li></ol>',
                'kategori' => 'keamanan',
                'platform' => '1Password',
                'url_resmi' => 'https://1password.com/students',
                'ikon' => 'fas fa-key',
                'warna' => 'kvt',
                'unggulan' => false,
                'urutan' => 30,
            ],
            [
                'judul' => 'Google Skillshop (Google Certifications)',
                'deskripsi' => 'Sertifikasi Google gratis: Google Ads, Analytics, Tag Manager, Google Marketing Platform. Diakui industri global.',
                'langkah' => '<ol><li>Kunjungi <a href="https://skillshop.withgoogle.com/" target="_blank">skillshop.withgoogle.com</a></li><li>Login dengan akun Google</li><li>Pilih sertifikasi: Google Ads, Analytics, dll</li><li>Pelajari modul dan selesaikan assessment</li><li>Ujian sertifikasi 100% gratis dan bisa diulang</li><li>Sertifikat valid 1 tahun dan bisa ditampilkan di LinkedIn</li></ol>',
                'kategori' => 'sertifikasi',
                'platform' => 'Google',
                'url_resmi' => 'https://skillshop.withgoogle.com/',
                'ikon' => 'fab fa-google',
                'warna' => 'green',
                'unggulan' => false,
                'urutan' => 31,
            ],
        ];

        foreach ($data as $item) {
            EdukasiGratis::create($item);
        }
    }
}
