# Cara mendukung KVT Hub secara finansial
# Ref: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: kuro-myths
# ko_fi: kvthub
# custom:
#   - https://kvthub.id/donasi
